n = int(input('Diga um número, e eu direi sua tabuada:'))
a = n*1
b = n*2
c = n*3
d = n*4
e = n*5
f = n*6
g = n*7
h = n*8
i = n*9
j = n*10
print(f'{n}x1={a}')
print(f'{n}x2={b}')
print(f'{n}x3={c}')
print(f'{n}x4={d}')
print(f'{n}x5={e}')
print(f'{n}x6={f}')
print(f'{n}x7={g}')
print(f'{n}x8={h}')
print(f'{n}x9={i}')
print(f'{n}x10={j}')
